name: Docker Image CI

on:
  push:
    branches:
    - master
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '10.19.0'
      - run: npm ci
      - run: echo "Tests running for server"

  build:
    name: Build, tag, and push app docker images
    uses: ./.github/workflows/buildapp.yml
    strategy:
      matrix:
        webchatbot-ecr-repo: ["webchatapp-backend-ecr", "webchatapp-frontend-ecr"]
