# on:
#   push:
#     branches:
#     - dev

jobs:

  build:
    permissions:
      id-token: write # This is required for requesting the JWT
    
    runs-on: ubuntu-latest

    steps:
    - run: echo Hello world!

    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ECR_ACCESS }}
        aws-region: us-east-2

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Test docker pull
      run: |
        docker pull 693373126778.dkr.ecr.us-east-2.amazonaws.com/webchatapp-backend-ecr:api-04
        docker image ls
