on:
  workflow_dispatch:

jobs:

  deploy-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare compose file with up-to-date envs
      env:
        APP_TAG="d23e745bd5d98bb2362e01a8b8a880538e492dd9"
      run: |
        echo "APP_TAG is $APP_TAG"
        envsubst < "docker-compose-aws_nobuild.tmpl" > "docker-compose.yaml"
    
    - name: Copy compose file
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DEPLOY_HOST  }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY_PROD }}
        source: "docker-compose.yaml"
        target: /app/docker-compose.yaml

    - name: Deploy app
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.DEPLOY_HOST  }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY_PROD }}
        script: |
          cd /app
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 693373126778.dkr.ecr.us-east-2.amazonaws.com
          docker compose up -d
